web:
  env:
  - name: CONCOURSE_EXTERNAL_URL
    value: http://concourse.infra.local/
  - name: CONCOURSE_OIDC_CLIENT_ID
    value: concourse
  - name: CONCOURSE_OIDC_CLIENT_SECRET
    value: 76Isfn72SyS3oye2GdnBUEym34q6useW
  - name: CONCOURSE_OIDC_ISSUER
    value: http://idp.infra.local/auth/realms/master
  - name: CONCOURSE_OIDC_DISPLAY_NAME
    value: Keycloak
  - name: CONCOURSE_OIDC_USER_NAME_KEY
    value: email

worker:
  env:
  # using cgroups v2
  - name: CONCOURSE_RUNTIME
    value: containerd
