web:
  externalUrl: concourse.kind
  extraEnvVars:
  - name: CONCOURSE_ADD_LOCAL_USER
    value: admin:admin
  - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
    value: admin

postgresql:
  enabled: false

externalDatabase:
  host: postgres-postgresql.db
  port: 5432
  user: concourse
  password: "secretconcoursepassword"
  database: concourse

service:
  web:
    type: ClusterIP