proxy:
  loadBalancerIP: 172.20.0.102

ingressController:
  enabled: false

env:
  log_level: info

securityContext:
  runAsUser: 0

dblessConfig:
  config: |
    _format_version: "1.1"
    services:
    - name: concourse
      url: http://concourse.kind
      routes:
      - name: concourse
        paths:
        - "/"