apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker
  namespace: argo
spec:
  serviceAccountName: gitea
  entrypoint: main
  # Shared workspace volume
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 64Mi
  templates:
    - name: main
      dag:
        tasks:
          - name: clone
            template: clone
            arguments:
              parameters:
                - name: repo
                  value: "{{workflow.parameters.repo}}"
                - name: branch
                  value: "{{workflow.parameters.branch}}"
          - name: image
            template: image
            arguments:
              parameters:
                - name: path
                  value: "{{workflow.parameters.image}}/{{workflow.parameters.branch}}"
                - name: image
                  value: "{{workflow.parameters.image}}"
            depends: "clone"
    - name: clone
      inputs:
        parameters:
          - name: repo
          - name: branch
      container:
        volumeMounts:
          - mountPath: /work
            name: work
        image: alpine/git:v2.26.2
        workingDir: /work
        args:
          - clone
          - "{{inputs.parameters.repo}}"
    - name: image
      inputs:
        parameters:
          - name: path
          - name: image
      container:
        image: moby/buildkit:v0.9.3
        volumeMounts:
          - name: work
            mountPath: /work
        workingDir: "/work/{{workflow.parameters.image}}"
        # need to run as privileged to build the image
        securityContext:
          privileged: true
        command:
          - buildctl-daemonless.sh
        args:
          - build
          - --frontend
          - dockerfile.v0
          - --local
          - context=.
          - --local
          - dockerfile=.
          - --output
          - type=image,name=docker.io/{{inputs.parameters.image}}
