servers:
- zones:
  - zone: local
  port: 53
  plugins:
  - name: template
    parameters: ANY ANY local
    configBlock: |-
      answer "{{ .Name }} 60 IN A 172.18.255.200"

  # Need this for the service to be available
  - name: ready
  - name: health
    configBlock: |-
      lameduck 5s

# This is not dns for the k8s cluster.  It's an app.
isClusterService: false

replicaCount: 2