# this is edited by tf.  Array order is important
servers:
- zones:
  - zone: local
  port: 53
  plugins:
  - name: template
    parameters: ANY ANY local
    # config block is the param edited to update the
    configBlock: |-
      answer "{{ .Name }} 60 IN A 127.0.0.1"

  # Need this for the service to be available / pass health checks.
  - name: ready
  - name: health
    configBlock: |-
      lameduck 5s

# Set to false if you don't want coredns to be service for k8s itself.
# Setting it to false allows you to use coredns as an external service.
isClusterService: false

replicaCount: 2