ingressController:
  enabled: false

proxy:
  type: ClusterIP

dblessConfig:
  config: |
    _format_version: "2.1"

    services:
    - name: concourse
      url: http://concourse-web.concourse.svc.cluster.local:8080
      routes:
      - name: concourse
        hosts:
        - concourse.infra.local
    - name: gitea
      url: http://gitea-http.gitea.svc.cluster.local:3000
      routes:
      - name: gitea
        hosts:
        - gitea.infra.local
    - name: keycloak
      url: http://bitnami-keycloak.keycloak.svc.cluster.local
      routes:
      - name: keycloak
        hosts:
        - idp.infra.local
