apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker
  namespace: argo
spec:
  serviceAccountName: gitea
  entrypoint: checkout
  templates:
    - name: checkout
      inputs:
        parameters:
          - name: repo
          - name: branch
      volumes:
        - name: work
          emptyDir: {}
      container:
        image: alpine/git:v2.32.0
        workingDir: /work
        args:
          - clone
          - "{{workflow.parameters.repo}}"
        volumeMounts:
          - mountPath: /work
            name: work
    - name: image
      inputs:
        parameters:
          # Name of the image to push
          - name: image
      # Mount the configuration so we can push the image.
      # This should create the /.docker/config.json file.
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
        - name: work
          emptyDir: {}
      container:
        image: moby/buildkit:v0.7.2-rootless
        volumeMounts:
          - name: work
            mountPath: /work
          - name: docker-config
            mountPath: /.docker
        workingDir: /work/
        env:
          - name: BUILDKITD_FLAGS
            value: --oci-worker-no-process-sandbox
          - name: DOCKER_CONFIG
            value: /.docker
        command:
          - buildctl-daemonless.sh
        args:
          - build
          - --frontend
          - dockerfile.v0
          - --local
          - context=.
          - --local
          - dockerfile=.
          - --output
          - type=image,name=docker.io/{{inputs.parameters.image}},push=true