apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sample
  namespace: argo
spec:
  # need a service account that can "watch" pods
  serviceAccountName: gitea
  templates:
    - name: main
      inputs:
        parameters:
          - name: message
            value: "{{workflow.parameters.message}}"
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
  entrypoint: main
