replicaCount: 1
isClusterService: false
servers:
- port: 53
  zones:
  - zone: kind.
  - zone: internal.
  plugins:
  - name: template
    # TODO probs better way to do parameters
    parameters: ANY ANY kind.
    configBlock: |
      answer "{{ .Name }} 60 IN A 172.20.0.102"
    # TODO single source IP address
  - name: template
    parameters: ANY ANY db.internal.
    configBlock: |
      answer "db.internal 60 IN A 172.20.0.101"
  - name: ready
  - name: health
    configBlock: lameduck 5s
serviceType: LoadBalancer
service:
  loadBalancerIP: 172.20.0.100
