config:
  # Set it to a valid URL
  issuer: http://idp.infra.local

  # See https://dexidp.io/docs/storage/ for more options
  storage:
    type: memory

  # Enable at least one connector
  # See https://dexidp.io/docs/connectors/ for more options
  enablePasswordDB: true

  staticClients:
  - id: concourse
    secret: concourse-secret
    name: 'Concourse'
    # Where the app will be running.
    redirectURIs:
    - 'http://concourse.infra.local/sky/issuer/callback'


  staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"