apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: docker
  namespace: argo
spec:
  event:
    selector: payload.repository.name != ""
  submit:
    workflowTemplateRef:
      name: docker
    arguments:
      parameters:
      - name: repo
        valueFrom:
          event: payload.repository.clone_url
      - name: branch
        valueFrom:
          event: payload.ref
      - name: image
        valueFrom:
          event: payload.repository.name