configInline:
  address-pools:
    - name: default
      protocol: layer2
      addresses:
      # If these are wrong, check the IP in kubectl get nodes -o wide. Has to match the 172.X subnet
      - 172.19.255.200-172.19.255.202