web:
  env:
  - name: CONCOURSE_EXTERNAL_URL
    value: http://concourse.infra.local/
  - name: CONCOURSE_OIDC_DISPLAY_NAME
    value: Keycloak
  - name: CONCOURSE_OIDC_USER_NAME_KEY
    value: email

worker:
  env:
  # using cgroups v2
  - name: CONCOURSE_RUNTIME
    value: containerd
